export const Users = [
  {
    id: 1,
    profilePicture: process.env.REACT_APP_PUBLIC_FOLDER + "person/1.jpg",
    username: "Pranav Dubey",
  },
  {
    id: 2,
    profilePicture: process.env.REACT_APP_PUBLIC_FOLDER + "person/2.jpg",
    username: "Sankalp Dwivedi",
  },
  {
    id: 3,
    profilePicture: process.env.REACT_APP_PUBLIC_FOLDER + "person/3.jpg",
    username: "Raghav Awasthi",
  },
  {
    id: 4,
    profilePicture: process.env.REACT_APP_PUBLIC_FOLDER + "person/4.jpg",
    username: "Tanu",
  },
  {
    id: 5,
    profilePicture: process.env.REACT_APP_PUBLIC_FOLDER + "person/5.jpg",
    username: "Sansakr Singh",
  },
  {
    id: 6,
    profilePicture: process.env.REACT_APP_PUBLIC_FOLDER + "person/6.jpg",
    username: "Dandi",
  },
  {
    id: 7,
    profilePicture: process.env.REACT_APP_PUBLIC_FOLDER + "person/7.jpg",
    username: "Manu",
  },
  {
    id: 8,
    profilePicture: process.env.REACT_APP_PUBLIC_FOLDER + "person/8.jpg",
    username: "Mratyunjay",
  },
  {
    id: 9,
    profilePicture: process.env.REACT_APP_PUBLIC_FOLDER + "person/9.jpg",
    username: "Prasoon Singh",
  },
  {
    id: 10,
    profilePicture: process.env.REACT_APP_PUBLIC_FOLDER + "person/10.jpg",
    username: "Ayush Sharma",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: process.env.REACT_APP_PUBLIC_FOLDER + "post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: process.env.REACT_APP_PUBLIC_FOLDER + "post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: process.env.REACT_APP_PUBLIC_FOLDER + "post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: process.env.REACT_APP_PUBLIC_FOLDER + "post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: process.env.REACT_APP_PUBLIC_FOLDER + "post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: process.env.REACT_APP_PUBLIC_FOLDER + "post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: process.env.REACT_APP_PUBLIC_FOLDER + "post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: process.env.REACT_APP_PUBLIC_FOLDER + "post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: process.env.REACT_APP_PUBLIC_FOLDER + "post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: process.env.REACT_APP_PUBLIC_FOLDER + "post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
